name: gun
version: 1.5.0
description: Tool for Simplifying Dart Development
author: Kenneth Endfinger <kaendfinger@gmail.com>
homepage: https://github.com/DirectMyFile/gun
dependencies:
  http: ">=0.11.2 <0.12.0"
executables:
  gun: gun
